
[package]
authors = ["jlow8697@gmail.com"]
edition = "2021"
name = "slither_native"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
serde_json = "1"

[build-dependencies]
napi-build = "2"

[profile.release]
opt-level = 3         # Maximum optimizations (Default for release)
lto = "fat"           # Aggressive Link-Time Optimization for speed
codegen-units = 1     # Slower compile, but better optimization
panic = "abort"       # Removes stack unwinding code to reduce binary size and overhead
debug = true          # KEPT: Needed for samply/flamegraph reports
strip = false         # KEPT: Ensures symbols aren't deleted so you can read function names
