/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class World {
  tickId: number
  constructor(settings: WorldSettings)
  getSettings(): WorldSettings
  getSnakes(): Array<Snake>
  getPellets(): Array<Pellet>
  step(): void
}

export interface Brain {
  weights: Array<number>
  inputSize: number
  layerSizes: Array<number>
}

export interface Pellet {
  x: number
  y: number
  value: number
  type: string
}

export interface Snake {
  id: number
  x: number
  y: number
  dir: number
  alive: boolean
  pointsScore: number
  brain: Brain
}

export interface Vector2 {
  x: number
  y: number
}

export interface WorldSettings {
  worldRadius: number
  snakeCount: number
  pelletCount: number
  tickRate: number
}
