/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class World {
  tickId: number
  constructor(settings: WorldSettings)
  step(): void
  getSettings(): WorldSettings
  getSnakes(): Array<Snake>
  getPellets(): Array<Pellet>
}

export interface Brain {
  weights: Array<number>
  inputSize: number
  layerSizes: Array<number>
  /**
   * Flattened layer types: 0=Dense, 1=Gru, 2=Lstm, 3=Rru.
   * Matches the stack order.
   */
  layerTypes: Array<number>
  /** Recurrent state buffer (flattened) */
  state: Array<number>
}

export interface Pellet {
  x: number
  y: number
  value: number
  type: string
}

export interface Snake {
  id: number
  x: number
  y: number
  dir: number
  alive: boolean
  pointsScore: number
  brain: Brain
  speed: number
  radius: number
  targetLen: number
  boost: number
  turnInput: number
  points: Array<Vector2>
}

export interface Vector2 {
  x: number
  y: number
}

export interface WorldSettings {
  worldRadius: number
  snakeCount: number
  pelletCount: number
  tickRate: number
}
